#!/bin/env bash
usage() {
  echo "usage: dotfiles-cli"
  echo "  -h, --help"
  echo "          Shows This Text"
  echo "  -i, --install"
  echo "          Install the dot files"
  echo "  -u, --update"
  echo "          Updates the dot files"
}

copy-dotfiles() {
  for i in /usr/share/dotfiles/*; do
    u="$(basename $i)"
    z="$(echo ~/.config/$u)"
    for o in $i/*; do
      echo "Copying $o to $z"
      cp $o $z -r
    done
  done
}

install() {
  for i in /usr/share/dotfiles/*; do
    u="$(basename $i)"
    z="$(echo ~/.config/$u)"
    echo "Removing $z"
    rm -rf $z
    mkdir $z
  done
  copy-dotfiles
}

if [[ $1 == "--help " || $1 == "-h" ]]; then
  usage
  exit 0
elif [[ $1 == "--install" || $1 == "-i" ]]; then
  install
  exit 0
elif [[ $1 == "--update" || $1 == "-u" ]]; then
  copy-dotfiles
  exit 0
else
  usage
  exit 1
fi
