#!/bin/env bash

if [ "$EUID" -ne 0 ]; then
  echo "Please, run script as root"
  exit 255
fi

if ! grep cachyos /etc/pacman.conf &>/dev/null; then
  curl https://mirror.cachyos.org/cachyos-repo.tar.xz -o /tmp/cachyos-repo.tar.xz
  cd /tmp/
  tar xvf cachyos-repo.tar.xz && cd cachyos-repo
  ./cachyos-repo.sh
fi

if ! grep chaotic-aur /etc/pacman.conf &>/dev/null; then
  pacman-key --recv-key 3056513887B78AEB --keyserver keyserver.ubuntu.com
  pacman-key --lsign-key 3056513887B78AEB
  pacman -U --needed 'https://cdn-mirror.chaotic.cx/chaotic-aur/chaotic-keyring.pkg.tar.zst'
  pacman -U --needed 'https://cdn-mirror.chaotic.cx/chaotic-aur/chaotic-mirrorlist.pkg.tar.zst'
  echo '' | tee -a /etc/pacman.conf
  echo '[chaotic-aur]' | tee -a /etc/pacman.conf
  echo 'Include = /etc/pacman.d/chaotic-mirrorlist' | tee -a /etc/pacman.conf
fi
if ! grep universe /etc/pacman.conf &>/dev/null; then
  echo '' | tee -a /etc/pacman.conf
  echo '[universe]' | tee -a /etc/pacman.conf
  echo 'SigLevel = Optional DatabaseOptional' | tee -a /etc/pacman.conf
  echo 'Server = https://github.com/jens-buehnen/universe-core-repo/raw/refs/heads/master/$arch' | tee -a /etc/pacman.conf
fi
