#!/bin/env bash
if command -v yay &>/dev/null; then
  yay
  yay -Sc --noconfirm
fi
if command -v flatpak &>/dev/null; then
  doas flatpak update
  doas flatpak uninstall --unused
fi
if command -v brew &>/dev/null; then
  brew upgrade
  brew update
fi
