#!/bin/env bash
usage() {
  echo "usage: dot-files"
  echo "  -h, --help"
  echo "          Shows This Text"
  echo "  -i, --install"
  echo "          Install the dot files"
  echo "  -u, --update"
  echo "          Updates the dot files"
}

copy-dot-files() {
  for i in /usr/share/dot-files/*; do
    u="$(basename $i)"
    z="$(echo ~/.config/$u)"
    for o in $i/*; do
      cp $o $z -r
    done
  done
}

install() {
  for i in /usr/share/dot-files/*; do
    u="$(basename $i)"
    z="$(echo ~/.config/$u)"
    rm -rf $z
    mkdir $z
    copy-dot-files
  done
}

if [[ $1 == "--help " || $1 == "-h" ]]; then
  usage
  exit 0
elif [[ $1 == "--install" || $1 == "-i" ]]; then
  install
  exit 0
elif [[ $1 == "--update" || $1 == "-u" ]]; then
  copy-dot-files
  exit 0
else
  usage
  exit 1
fi
